#!/bin/bash
if [ "$#" -ne 2 ]; then
    echo "Usage: ./testhttp <cookies_file> <tested_http_address>"
    exit 1
fi

if [[ $2 = http://* ]] ; then
  address_port=${2#"http://"}
  address_port=${address_port%%/*}
  port=${address_port#*:}
  address=${address_port%:*}
  if [[ $port == $address_port ]] ; then
    port="80"
  fi
  ./testhttp_raw $address:$port $1 $2
else
  address_port=${2#"https://"}
  address_port=${address_port%%/*}
  port=${address_port#*:}
  address=${address_port%:*}
  if [[ $port == $address_port ]] ; then
    port="443"
  fi
  cat > stunnel.conf << ENDOFFILE
pid = $PWD/stunnel.pid
[service]
client = yes
accept = 127.0.0.1:3333
connect = $address:$port
ENDOFFILE
  stunnel stunnel.conf
  ./testhttp_raw 127.0.0.1:3333 $1 $2
  pid=`cat stunnel.pid`
  kill $pid
fi

exit 0
